### ISSUE TITLE
OrderSystem  / pathfinding strang path

### ISSUE THREAD

**Issue by xoniuqe** [WildRumbleOrga/SilentInfiltration#1]
The ordersystem or the pathfinding has a bug: 
The entity starts traversing the path always by stepping a tile "up" ( to the upper left hand corner of the display.

**Comment by Cataract92** [comment]
Going to rework the whole ordersystem.

**Comment by Cataract92** [comment]
Still a few bugs, but i can't test it properly if the RenderIssue https://github.com/WildRumbleOrga/SilentInfiltration/issues/2 is not fixed.

**Comment by Cataract92** [comment]
closed -> Port to Libgdx
