### ISSUE TITLE
Order or MoveSystem walks to wrong tile

### ISSUE THREAD

**Issue by xoniuqe** [WildRumbleOrga/SilentInfiltration#16]
The move or order system moves the units to the wrong tile? Could be an tilemap error but i found nothing there.

**Comment by Cataract92** [comment]
which pathfinder are you using and in which branch?

**Comment by xoniuqe** [comment]
Master branch.

**Comment by Cataract92** [comment]
center tilemap or change coordToIndex

**Comment by Cataract92** [comment]
reworked
