### ISSUE TITLE
Use library?

### ISSUE THREAD

**Issue by xoniuqe** [WildRumbleOrga/SilentInfiltration#22]
Maybe we find a nice and easy usable library for network that we can use. But on the other hand the java networking seems to be a quite easy job?

**Comment by Cataract92** [comment]
It's totally up to you. I liked the networking we done in the uni. But it was a simple one and i can image there's alot more to consider. (As you already said)

**Comment by xoniuqe** [comment]
Decided to use Kryonet.
@EsotericSoftware
