### ISSUE TITLE
Change of the collision system

### ISSUE THREAD

**Issue by xoniuqe** [WildRumbleOrga/SilentInfiltration#23]
The current collision system does not fit my needs, i would appreciate it if it would be changed.

The collision component should just hold an instance of an new collisionshape class (or something similiar) which contains a method for collision checking, a shape and maybe a position (but the last point could be redundant to the position class and irrelevant)

So the collision handling would work on different shapes and would be called in the concerning systems. 

This would make it much easier to assign colliders dynamically and the best, to change them easily. Currently we only have a rectangular node collider and a circular collider for entities, which is very limited (not only because the node component will be deleted in a few days)

Greetings :)

**Comment by Cataract92** [comment]
Rectangles for nonmoveable objects und circles for moveable objects.
