### ISSUE TITLE
Think about Objectaccessibility

### ISSUE THREAD

**Issue by Cataract92** [WildRumbleOrga/SilentInfiltration#24]
There're quite a few objects left we propably just need one instance from. E.g Pathfinder or CircularContextMenu.

How should we make them reachable from everywhere we need them, without making them public static in MiH or passing them with arguments.
Maybe a class which defines the map we are playing in with all the stuff we need.
And to get them we could use Map.getCurrentMap().getPathfinder().doawesomestuff().
Suggestions?

**Comment by xoniuqe** [comment]
Lets discuss this the upcoming week with a few beverages :D

**Comment by Cataract92** [comment]
added Game-Wrapper

**Comment by xoniuqe** [comment]
I think we should refactor the project and redesign the parts were singletons are used.
Discuss: #33
