### ISSUE TITLE
Finish StatC

### ISSUE THREAD

**Issue by Cataract92** [WildRumbleOrga/SilentInfiltration#29]
finish StatC

**Comment by xoniuqe** [comment]
I would prefer to discuss this component a bit more, concerning the possible values and stats that could be saved.

**Comment by Cataract92** [comment]
I implemented the .cpy() and setField() method in a way that we can easy add and remove values and stats even in later states of the game.
Edit: Forgot the add the StatsC to the index O.o

**Comment by xoniuqe** [comment]
I close this, because I think it is to early in the development for such detailled questions concerning a not completely planned game design.
