### ISSUE TITLE
ContextMenu problems with screen resize

### ISSUE THREAD

**Issue by xoniuqe** [WildRumbleOrga/SilentInfiltration#3]
![bug](https://cloud.githubusercontent.com/assets/4237103/9699210/7fbf0178-53da-11e5-9b2c-d1e0934027ff.png)

The context menu is rendered at the wrong position if the screen is resized

**Comment by Cataract92** [comment]
fixed.
use 
`spriteBatch.getProjectionMatrix().setToOrtho2D(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());` 
before rendering,
