### ISSUE TITLE
Remove logic of all components

### ISSUE THREAD

**Issue by xoniuqe** [WildRumbleOrga/SilentInfiltration#35]
Some components do more than just store data, this has to be changed.

**Comment by Cataract92** [comment]
The only Components with logic i can find are PositionC, ColliderC and VisualC. And PositionC and ColliderC are just complex setter and getters, so i would leave them. VisualC can be discussed, but i can't think on a good place to manipulate the visual other than the component.

**Comment by xoniuqe** [comment]
VisualC should not check for a collision component and try to manipulate it, this should be done in the system that makes the change - this is no task for the visual component. The same goes for the position component, why should itself set the concerning collider? As far as I know the collision systems always uses the position component and ignores the "position" of the collider.
And with the calculation of the navpoints in the collider im not shure if that should be done inside this component or maybe in some class for the pathgeneration, but this can be discussed.

**Comment by Cataract92** [comment]
Done. Only Getter and Setter left
