### ISSUE TITLE
Ordersystem

### ISSUE THREAD

**Issue by xoniuqe** [WildRumbleOrga/SilentInfiltration#40]
How exactly does the ordersystem work? I don´t quite understand it in the current state and think maybe it should be reworked too?

**Comment by Cataract92** [comment]
If your entity can take orders it has an OrderableC. If you now want the entity to move you add a new MoveOrder() to the Component (atm it's just one Order...has to be changed to a  e.g. queue) via order.newOrder(new MoveOrder()). Every Order has a handle() funktion which describes the logic behind the order. Now the OrderSystem iterates over all enities with an OrderableC and fires the handle() function of it's current order.

**Comment by xoniuqe** [comment]
Then we need maybe some kind of manager class , so we can be sure all needed systems/ managers are accessible, because I removed the singletons.

**Comment by xoniuqe** [comment]
I removed the task classes of the order system, because they were not needed and added only redundancy
